name: CI
on: [push, pull-request]
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

     - name: Install Forge
       run: cargo install --git https://github.com/gakonst/foundry --bin forge --locked

     - name: Forge version
       run: forge --version